[package]
name = "kurvix"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_asset_loader = { version = "0.22", features = ["2d"] }
rand = "0.8"

[profile.release]
opt-level = 'z'
strip = true
lto = true
